
insert into users values('1', 'Bishant', 'Bhattarai', 'BISHANT345@GMAIL.COM', '0', '0', 'd167f46c1030d3d6239a22bf775be730', '07/07/2000', 'M', 'img/22050319_2043307205897797_4365563192648790655_n.jpg');
insert into users values('2', 'Shaibya', 'Bhandari', 'SHAIBYABHANDARI18@GMAIL.COM', '0', '0', 'd167f46c1030d3d6239a22bf775be730', '05/09/1999', 'M', 'img/shaibya.jpg');
insert into users values('3', 'Laxhit', 'kadayat', 'LAXHIT007@GMAIL.COM', '0', '0', 'd167f46c1030d3d6239a22bf775be730', '04/01/1999', 'M', 'img/laxhit.jpg');
insert into users values('4', 'Sanket', 'Gautam', 'SANKETGAUTAM08@GMAIL.COM', '0', '0', 'd167f46c1030d3d6239a22bf775be730', '07/07/1998', 'M', 'img/sanket.jpg');
insert into users values('5', 'Nabin', 'Atreya', 'ATREYANABIN@GMAIL.COM', '0', '0', 'd167f46c1030d3d6239a22bf775be730', '09/03/1998', 'M', 'img/nabin.jpg');

insert into trader values('1', 'BAKERY', 'I prefer bakery items', '1', '9864579044', '1', 'd167f46c1030d3d6239a22bf775be730');
insert into trader values('2', 'GREENGROCER', 'I prefer greeny items', '2', '9867279310', '1', 'd167f46c1030d3d6239a22bf775be730');
insert into trader values('3', 'BUTCHER', 'I prefer non-veg items', '3', '9864512345', '1', 'd167f46c1030d3d6239a22bf775be730');
insert into trader values('4', 'DELICATESSEN', 'I prefer delicatessen haha', '4', '9862232768', '1', 'd167f46c1030d3d6239a22bf775be730');
insert into trader values('5', 'FISHMONGER', 'I prefer Fishes lol', '5', '9864234532', '1', 'd167f46c1030d3d6239a22bf775be730');


INSERT INTO SHOP values('1', 'Cake Station', 'Leeds', '1', 'img/shop1.jpg');
INSERT INTO SHOP values('2', 'Cheesy Bread', 'Brick Lane', '1', 'img/shop2.jpg');
INSERT INTO SHOP values('3', 'GreenBay', 'Carnaby', '2', 'img/shop3.jpg');
INSERT INTO SHOP values('4', 'Ester Green', 'Piccadilly', '2', 'img/shop4.jpg');
INSERT INTO SHOP values('5', 'Pack Butchers', 'Oxford', '3', 'img/shop5.jpg');
INSERT INTO SHOP values('6', 'British Butchers', 'Abbey Road', '3', 'img/shop6.jpg');
INSERT INTO SHOP values('7', 'The Hungry Guest', 'Baker Streets', '4', 'img/shop7.jpg');
INSERT INTO SHOP values('8', 'Wallys Store', 'Columbia Road', '4', 'img/shop8.jpg');
INSERT INTO SHOP values('9', 'FerryBridge', 'Savile Row', '5', 'img/shop9.jpg');


Insert into product_type values('1', 'Eggless Cakes', '1', 'A collection of bread recipes of famous restaurants globally, bread matter, online articles about adsense, Restaurants, Bakery,Cooking, food, blogging, SEO, Make Money Online, bread recipes, Work from Home, about Life and anything in between.' );
Insert into product_type values('99', 'Sugarless Cakes', '1', 'A collection of bread recipes of famous restaurants globally, bread matter, online articles about adsense, Restaurants, Bakery,Cooking, food, blogging, SEO, Make Money Online, bread recipes, Work from Home, about Life and anything in between.' );
Insert into product_type values('6', 'Cruchy Breads', '2', 'A collection of bread recipes of famous restaurants globally, bread matter, online articles about adsense, Restaurants, Bakery,Cooking, food, blogging, SEO, Make Money Online, bread recipes, Work from Home, about Life and anything in between.' );
Insert into product_type values('2', 'Leafy Green', '3', 'Greengrocer is primarily a British and Australian term, and greengrocers shops were once common in cities, towns and villages. They have been affected by the dominant rise of supermarkets, but many can be found managing small shops or stores in towns and cities and in some villages. Greengrocers can also be found in street markets and malls, or managing produce departments at supermarkets. Such traders typically handle the entire business of buying, selling, and book-keeping themselves.' );
Insert into product_type values('3', 'Soft Beef', '5', 'A butcher is a person who may slaughter animals, dress their flesh, sell their meat, or participate within any combination of these three tasks. They may prepare standard cuts of meat and poultry for sale in retail or wholesale food establishments. A butcher may be employed by supermarkets, grocery stores, butcher shops and fish markets, slaughter houses, or may be self-employed.' );
Insert into product_type values('4', 'Frozen Foods', '7', '‘Delikatesse’ meaning ‘a delicacy, fine food’. German borrowed the word from the French ‘délicatesse’ which was itself borrowed from the Italian ‘delicatezza’. The informal short form deli started to be used in print in the mid 20th century, although it had probably been in use in speech for some time' );
Insert into product_type values('5', 'Boneless fish', '9', 'A fishmonger (fishwife for female practitioners) is someone who sells raw fish and seafood. Fishmongers can be wholesalers or retailers, and are trained at selecting and purchasing, handling, gutting, boning, filleting, displaying, merchandising and selling their product. In some countries modern supermarkets are replacing fishmongers who operate in shops or fish markets.' );
Insert into product_type values('7', 'Fruits', '4', 'Greengrocer is primarily a British and Australian term, and greengrocers shops were once common in cities, towns and villages. They have been affected by the dominant rise of supermarkets, but many can be found managing small shops or stores in towns and cities and in some villages. Greengrocers can also be found in street markets and malls, or managing produce departments at supermarkets. Such traders typically handle the entire business of buying, selling, and book-keeping themselves.' );
Insert into product_type values('8', 'Boneless Meat', '6', 'A butcher is a person who may slaughter animals, dress their flesh, sell their meat, or participate within any combination of these three tasks. They may prepare standard cuts of meat and poultry for sale in retail or wholesale food establishments. A butcher may be employed by supermarkets, grocery stores, butcher shops and fish markets, slaughter houses, or may be self-employed.' );
Insert into product_type values('9', 'Healthy Salads', '8', '‘Delikatesse’ meaning ‘a delicacy, fine food’. German borrowed the word from the French ‘délicatesse’ which was itself borrowed from the Italian ‘delicatezza’. The informal short form deli started to be used in print in the mid 20th century, although it had probably been in use in speech for some time');



Insert into product VALUES('1', 'Black Forest', 'The cake is a triumph of sugar and flour, towering with buttercream and strawberries to bring it that celebratory colour and freshness. This Victoria sponge is birthday cake, the sort my son loves best. He craves the simplicity over the complex. A cake is a cake, beautiful as it is.', '500', '20', '1', '10', '../img/blackforest.jpg', '10', 'No allergy', '1', '1');
Insert into product VALUES('2', 'Chocolaty Doughnut', 'Doughnuts are usually deep fried from a flour dough, and typically either ring-shaped or a number of shapes without a hole, and often filled, but can also be ball-shaped ("doughnut holes").', '50', '50', '1', '10', 'img/doughnut1.jpg', '10', 'No allergy', '1', '0');
Insert into product VALUES('99', 'Chocolate Cherries', 'The cake is a triumph of sugar and flour, towering with buttercream and strawberries to bring it that celebratory colour and freshness. This Victoria sponge is birthday cake, the sort my son loves best. He craves the simplicity over the complex. A cake is a cake, beautiful as it is.', '500', '20', '1', '10', '../img/Chocolate cake with raspberries.jpg', '10', 'No allergy', '99', '1');
Insert into product VALUES('100', 'Sugerless Sweets', 'Doughnuts are usually deep fried from a flour dough, and typically either ring-shaped or a number of shapes without a hole, and often filled, but can also be ball-shaped ("doughnut holes").', '50', '50', '1', '10', 'img/chocolate cake.jpg', '10', 'No allergy', '99', '0');
Insert into product VALUES('3', 'Farm Cabbagge', 'Cabbages are one of the oldest domesticated plants, having been used as early as 7,500 to 5,000 BC. Pumpkins are widely grown for commercial use and as food, aesthetics, and recreational purposes. Pumpkin pie, for instance, is a traditional part of Thanksgiving meals in Canada and the United States, and pumpkins are frequently carved as jack-o-lanterns for decoration around Halloween.', '200', '26', '1', '5', '../img/cabbage2.jpg', '10', 'No allergy', '2', '0');
Insert into product VALUES('4', 'Fresh Pumpkin', 'Pumkin is a juicy stone fruit (drupe) produced from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit.', '200', '400', '1', '19', 'img/ps3.jpg', '10', 'No allergy', '2', '1');
Insert into product VALUES('5', 'Soft Beef Liver', 'Beef is the most common type of poultry in the world. Owing to the relative ease and low cost of raising them in comparison to animals such as cattle or hogs, chickens have become prevalent throughout the cuisine of cultures around the world, and their meat has been variously adapted to regional tastes.', '400', '250', '1', '15', '../img/beef3.jpg', '10', 'No allergy', '3', '1');
Insert into product VALUES('6', 'Local Goat Meat', 'Goat is a hardy domesticated ruminant mammal that has backward-curving horns and (in the male) a beard. It is kept for its milk and meat, and noted for its lively behaviour.', '1000', '455', '1', '10', 'img/beef2.jpg', '9', 'No allergy', '3', '1');
Insert into product VALUES('7', 'Veggies Salad', 'salad is a dish consisting of a mixture of small pieces of food, usually vegetables or fruit.However, different varieties of salad may contain virtually any type of ready-to-eat food. Salads are typically served at room temperature or chilled, with notable exceptions such as south German potato salad which can be served warm.', '100', '244', '1', '10', '../img/straw2.jpg', '10', 'No allergy', '9', '1');
Insert into product VALUES('8', 'Frozen Cheese', 'Cheese is a dairy product, derived from milk and produced in wide ranges of flavours, textures and forms by coagulation of the milk protein casein. It comprises proteins and fat from milk, usually the milk of cows, buffalo, goats, or sheep.', '300', '235', '1', '23', 'img/cheese1.jpg', '10', 'No allergy', '4', '1');
Insert into product VALUES('9', 'Carp Fish', 'Carp are various species of oily freshwater fish from the family Cyprinidae, a very large group of fish native to Europe and Asia. While carp is consumed in many parts of the world, they are generally considered as invasive species in parts of Africa, Australia and most of the United States.', '900', '240', '1', '11', '../img/carp1.jpg', '10', 'No allergy', '5', '0');
Insert into product VALUES('10', 'Salmon Fish', 'Fish have extremely high levels of c	hemicals such as arsenic, mercury, PCBs, DDT, dioxins, and lead in their flesh and fat. You may even get industrial-strength fire retardant with that catch of the day. The chemical residue found in salmon flesh can be as much as 9 million times that of the water in which they live.', '800', '200', '1', '5', '../img/salmon1.jpg', '10', 'No allergy', '5', '1');
Insert into product VALUES('11', 'Fresh Cupcake', 'The cake is a triumph of sugar and flour, towering with buttercream and strawberries to bring it that celebratory colour and freshness. This Victoria sponge is birthday cake, the sort my son loves best. He craves the simplicity over the complex. A cake is a cake, beautiful as it is.', '500', '20', '1', '10', '../img/cupcake1.jpg', '10', 'No allergy', '6', '1');
Insert into product VALUES('12', 'Sweet Pastry', 'The cake is a triumph of sugar and flour, towering with buttercream and strawberries to bring it that celebratory colour and freshness. This Victoria sponge is birthday cake, the sort my son loves best. He craves the simplicity over the complex. A cake is a cake, beautiful as it is.', '500', '20', '1', '10', '../img/pastry3.jpg', '10', 'No allergy', '6', '1');
Insert into product VALUES('13', 'Whole Chicken', 'Chicken is the most common type of poultry in the world. Owing to the relative ease and low cost of raising them in comparison to animals such as cattle or hogs, chickens have become prevalent throughout the cuisine of cultures around the world, and their meat has been variously adapted to regional tastes.', '400', '250', '1', '15', '../img/chicken2.jpg', '10', 'No allergy', '8', '1');

INSERT INTO REVIEW values('1', '1', '4', 'Very Tasty Definitely gonna buy this again!', '1');
INSERT INTO REVIEW values('2', '2', '4', 'Love this product will buy it again next time!', '2');
INSERT INTO REVIEW values('3', '3', '4', 'Very Tasty Definitely gonna buy this again!', '3');
INSERT INTO REVIEW values('4', '4', '4', 'Love this product will buy it again next time!', '4');
INSERT INTO REVIEW values('5', '5', '4', 'Very Tasty Definitely gonna buy this again!', '5');
INSERT INTO REVIEW values('6', '1', '4', 'Love this product will buy it again next time!', '6');
INSERT INTO REVIEW values('7', '2', '4', 'Very Tasty Definitely gonna buy this again!', '7');
INSERT INTO REVIEW values('8', '3', '4', 'Love this product will buy it again next time!', '8');
INSERT INTO REVIEW values('9', '4', '4', 'Very Tasty Definitely gonna buy this again!', '9');
INSERT INTO REVIEW values('10', '5', '4', 'Love this product will buy it again next time!', '10');
INSERT INTO REVIEW values('11', '1', '4', 'Love this product will buy it again next time!', '11');
INSERT INTO REVIEW values('12', '1', '4', 'Very Tasty Definitely gonna buy this again!', '12');
INSERT INTO REVIEW values('13', '1', '4', 'Very Tasty Definitely gonna buy this again!', '13');
INSERT INTO REVIEW values('14', '2', '4', 'Very Tasty Definitely gonna buy this again!', '99');
INSERT INTO REVIEW values('15', '3', '4', 'Very Tasty Definitely gonna buy this again!', '100');

INSERT INTO DISCOUNT values('1', '1', '4', '1');
INSERT INTO DISCOUNT values('2', '2', '5','1');
INSERT INTO DISCOUNT values('3', '3', '6', '2');
INSERT INTO DISCOUNT values('4', '4', '7', '2');
INSERT INTO DISCOUNT values('5', '7', '3', '9');

